In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('test_data.csv')

In [3]:
data

X1  X2    y
0  34   5  5.0
1  25   5  2.5
2  30   2  4.0
3  38  20  3.0
4  44  12  3.3
5  48  18  4.2
6  52  22  4.6
7  60  19  6.0
8  34  18  3.0
9  34  22  2.9

In [4]:
data_np = data.values

In [5]:
X = data_np[:,:-1]

In [71]:
X = np.insert(data_np[:,:-1], 0, np.ones(10), axis = 1)

In [6]:
X

array([[34.,  5.],
       [25.,  5.],
       [30.,  2.],
       [38., 20.],
       [44., 12.],
       [48., 18.],
       [52., 22.],
       [60., 19.],
       [34., 18.],
       [34., 22.]])

In [57]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [58]:
X

array([[-0.57281553, -1.27733275],
       [-1.44660194, -1.27733275],
       [-0.96116505, -1.68937557],
       [-0.18446602,  0.78288136],
       [ 0.39805825, -0.3158995 ],
       [ 0.78640777,  0.50818615],
       [ 1.17475728,  1.05757658],
       [ 1.95145631,  0.64553375],
       [-0.57281553,  0.50818615],
       [-0.57281553,  1.05757658]])

In [46]:
w_layer1 = np.random.rand(2,2) # Uniform distribution

In [47]:
w_layer1

array([[0.80474368, 0.81141451],
       [0.71697291, 0.46167356]])

In [48]:
b = np.random.rand(1,2)

In [49]:
b

array([[0.03047865, 0.1156648 ]])

In [59]:
H1_inputs = np.dot(X, w_layer1)+b

In [60]:
H1_inputs

array([[-1.34630402, -0.9388368 ],
       [-2.0494781 , -1.64783977],
       [-1.95424938, -1.44417851],
       [ 0.44333552,  0.32742202],
       [ 0.12432213,  0.29281259],
       [ 1.02769103,  0.98838358],
       [ 1.7341109 ,  1.55713505],
       [ 2.06373099,  1.99713063],
       [-0.06613533, -0.11450993],
       [ 0.32776273,  0.13912911]])

In [52]:
w_layer1_normal = np.random.normal(size=(2,2)) # Standard normal distribution

In [53]:
w_layer1_normal

array([[-0.10249279, -0.00229268],
       [ 0.34001789,  0.75667919]])

In [26]:
b_normal = np.random.normal(size=(1,2))

In [27]:
H1_inputs = np.dot(X, w_layer1_normal)+b_normal

In [28]:
H1_inputs.shape

(10, 2)

In [29]:
H1_inputs

array([[ 43.83467311, -39.94866812],
       [ 32.89294529, -27.06120407],
       [ 38.0904351 , -40.00088165],
       [ 53.1039026 , -16.77655331],
       [ 58.0483935 , -40.78146354],
       [ 64.67387938, -34.94927469],
       [ 70.71186668, -32.97040273],
       [ 79.5565991 , -50.20590165],
       [ 47.65341388, -14.90210839],
       [ 48.82841104,  -7.19547463]])

Sigmoid 활성화 함수 적용하기

In [61]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [62]:
H1_outputs = sigmoid(H1_inputs)

In [63]:
H1_outputs.shape

(10, 2)

In [64]:
H1_outputs

array([[0.20647528, 0.28113536],
       [0.11410513, 0.16140112],
       [0.12409075, 0.19089912],
       [0.60905353, 0.58113198],
       [0.53104056, 0.57268456],
       [0.73646801, 0.72876853],
       [0.84993749, 0.82594187],
       [0.88732772, 0.88049548],
       [0.48347219, 0.47140376],
       [0.58121491, 0.53472628]])

In [65]:
w_layer2 = np.random.rand(2,1)

In [66]:
w_layer2

array([[0.17865036],
       [0.34894062]])

In [67]:
b_layer2 = np.random.rand(1,1)

In [72]:
O1_inputs = np.dot(H1_outputs, w_layer2) + b_layer2

In [73]:
O1_inputs 

array([[0.62502797],
       [0.56674587],
       [0.57882285],
       [0.80162973],
       [0.78474503],
       [0.87590876],
       [0.93008785],
       [0.9558036 ],
       [0.74090594],
       [0.78046351]])

# 최종 출력

In [79]:
def identity_function(X):
    return X

In [81]:
O1_outputs = identity_function(O1_inputs)

In [82]:
O1_outputs # 종속변수에 대한 예측치

array([[0.62502797],
       [0.56674587],
       [0.57882285],
       [0.80162973],
       [0.78474503],
       [0.87590876],
       [0.93008785],
       [0.9558036 ],
       [0.74090594],
       [0.78046351]])